---
title: "DHS"
author: "Evelyn Annor"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#Getting work directory
getwd()

### Loading packages and open libraries
pacman::p_load(readr, tidyverse, nnet, MASS, funModeling, brant, broom, odds.n.ends)

#importing data
library(haven)
DHS_Contraceptive <- read_sav("DHS_Contraceptive.sav")
View(DHS_Contraceptive)

#Data CLEANING AND MANAGEMENT

#Getting labels of data
DHS_Contraceptive$"V457"<- as_factor(DHS_Contraceptive$"V457")
DHS_Contraceptive$"V313"<- as_factor(DHS_Contraceptive$"V313")
DHS_Contraceptive$"V312"<- as_factor(DHS_Contraceptive$"V312")
DHS_Contraceptive$"V190"<- as_factor(DHS_Contraceptive$"V190")
DHS_Contraceptive$"V106"<- as_factor(DHS_Contraceptive$"V106")
DHS_Contraceptive$"V013"<- as_factor(DHS_Contraceptive$"V013")
DHS_Contraceptive$"V024"<- as_factor(DHS_Contraceptive$"V024")
DHS_Contraceptive$"V025"<- as_factor(DHS_Contraceptive$"V025")
DHS_Contraceptive$"V130"<- as_factor(DHS_Contraceptive$"V130")
DHS_Contraceptive$"V131"<- as_factor(DHS_Contraceptive$"V131")
DHS_Contraceptive$"V213"<- as_factor(DHS_Contraceptive$"V213")
DHS_Contraceptive$"V404"<- as_factor(DHS_Contraceptive$"V404")
DHS_Contraceptive$"V405"<- as_factor(DHS_Contraceptive$"V405")
DHS_Contraceptive$"V447"<- as_factor(DHS_Contraceptive$"V447")
DHS_Contraceptive$"V445"<- as_factor(DHS_Contraceptive$"V445")
DHS_Contraceptive$"V454C"<- as_factor(DHS_Contraceptive$"V452C")
DHS_Contraceptive$"V455"<- as_factor(DHS_Contraceptive$"V455")

#Recoding BMI
names(DHS_Contraceptive)
str(DHS_Contraceptive$V445)
#Converting factor BMI into numeric before recoding
DHS_Contraceptive$BMI_raw <- as.numeric(as.character(DHS_Contraceptive$V445))
#Confirming it is truely numeric now
summary(DHS_Contraceptive$BMI_raw)
head(DHS_Contraceptive$BMI_raw)
#Converting now
DHS_Contraceptive$BMI <- DHS_Contraceptive$BMI_raw / 100

#Recoding Anemia continous data
str(DHS_Contraceptive$V453)
table(DHS_Contraceptive$V457 == 996)
table(DHS_Contraceptive$V457 == 994)
table(DHS_Contraceptive$V457 == 995)

#Converting factor BMI into numeric before recoding
DHS_Contraceptive$HB_raw <- as.numeric(as.character(DHS_Contraceptive$V453))
#Confirming it is truely numeric now
summary(DHS_Contraceptive$HB_raw)
head(DHS_Contraceptive$HB_raw)
#Converting now
DHS_Contraceptive$HB <- DHS_Contraceptive$HB_raw / 10

#Recoding contraceptive type into HORMONAL, NO METHOD AND OTHER METHODS
str(DHS_Contraceptive$V312)
#Checking methods labels
levels(DHS_Contraceptive$V312)

# Convert factor to character
method <- as.character(DHS_Contraceptive$V312)

# Creating new variable
DHS_Contraceptive$contraceptive_group <- NA

# 0 = No method
DHS_Contraceptive$contraceptive_group[method == "Not using"] <- "No method"

# 2 = Hormonal
DHS_Contraceptive$contraceptive_group[method %in% c("Pill",
                                                    "Injections",
                                                    "Implants/Norplant")] <- "Hormonal"

# 1 = Non-hormonal → all remaining non-missing methods
DHS_Contraceptive$contraceptive_group[
  is.na(DHS_Contraceptive$contraceptive_group) & !is.na(method)
] <- "Non-hormonal"

# Turn into ordered factor
DHS_Contraceptive$contraceptive_group <- factor(
  DHS_Contraceptive$contraceptive_group,
  levels = c("No method", "Non-hormonal", "Hormonal")
)

table(DHS_Contraceptive$contraceptive_group, useNA = "ifany")

#Recoding wealth index combined into rich,middle and poor
str(DHS_Contraceptive$V190)
#Converting factor into character
wealth <- as.character(DHS_Contraceptive$V190)
str(wealth)

# Creating empty variable
DHS_Contraceptive$wealth3 <- NA

# Poor group
DHS_Contraceptive$wealth3[wealth %in% c("Poorest", "Poorer")] <- "Poor"

# Middle group
DHS_Contraceptive$wealth3[wealth == "Middle"] <- "Middle"

# Rich group
DHS_Contraceptive$wealth3[wealth %in% c("Richer", "Richest")] <- "Rich"

DHS_Contraceptive$wealth3 <- factor(
  DHS_Contraceptive$wealth3,
  levels = c("Poor", "Middle", "Rich")
)


table(DHS_Contraceptive$wealth3, useNA = "ifany")

```


```{r}

#Making sure outcome variable is in the right order for ordinal logistic regression

levels(DHS_Contraceptive$V457)
table(DHS_Contraceptive$V457, useNA = "ifany")

#Setting other
DHS_Contraceptive$anemia <- factor(
  DHS_Contraceptive$V457,
  levels = c("Not anemic", "Mild", "Moderate", "Severe"),
  ordered = TRUE
)

#Checking the order
levels(DHS_Contraceptive$anemia)
table(DHS_Contraceptive$anemia, useNA = "ifany")

```



```{r}

#DESCRIPTIVES
library(table1)
DHS_Contraceptive$age   <- DHS_Contraceptive$V012   # age in years
DHS_Contraceptive$parity <- DHS_Contraceptive$V201  # total children

DHS_Contraceptive$anemia              <- DHS_Contraceptive$anemia       # ordered factor
DHS_Contraceptive$contraceptive_group <- factor(DHS_Contraceptive$contraceptive_group)
DHS_Contraceptive$V106                <- factor(DHS_Contraceptive$V106)  # education
DHS_Contraceptive$wealth3              <- factor(DHS_Contraceptive$wealth3)
DHS_Contraceptive$V130                <- factor(DHS_Contraceptive$V130)  # religion
DHS_Contraceptive$V025                <- factor(DHS_Contraceptive$V025)  # residence
DHS_Contraceptive$V024                <- factor(DHS_Contraceptive$V024)  # region

label(DHS_Contraceptive$age)                <- "Age"
units(DHS_Contraceptive$age)                <- "years"

label(DHS_Contraceptive$BMI)                <- "Body Mass Index"
units(DHS_Contraceptive$BMI)                <- "kg/m²"

label(DHS_Contraceptive$parity)             <- "Parity (children ever born)"
label(DHS_Contraceptive$anemia)             <- "Anemia status"
label(DHS_Contraceptive$contraceptive_group)<- "Contraceptive method group"
label(DHS_Contraceptive$V106)               <- "Education level"
label(DHS_Contraceptive$wealth3)             <- "Wealth index"
label(DHS_Contraceptive$V130)               <- "Religion"
label(DHS_Contraceptive$V025)               <- "Residence"
label(DHS_Contraceptive$V024)               <- "Region"


table1(
  ~ age + BMI + parity +
    anemia +
    contraceptive_group +
    V106 + wealth3 + V130 + V025 + V024,
  data = DHS_Contraceptive
)
```



```{r}
#Reasearch onjective 1,
#To determine whether current use of hormonal contraceptives is associated with anemia severity (none, mild, moderate, severe) among non-pregnant women aged 15- 49, in Ghana, 2022.

#Importing libary to run ordinal logistic regression
library(MASS)

model1 <- polr(
  anemia ~ contraceptive_group,
  data = DHS_Contraceptive,
  Hess = TRUE
)

summary(model1)


#Getting the p-value
(ctable <- coef(summary(model1)))
p_values <- 2 * pnorm(abs(ctable[, "t value"]), lower.tail = FALSE)
cbind(ctable, "p value" = p_values)

#Getting confidence interval
OR <- exp(coef(model1))
CI <- exp(confint(model1))
cbind(OR, CI)
```



```{r}

#Adjusting the model with variable from DAG and literature
#V012=AGE
#V201=PARITY
#V106=EDUCATION

model1_adj <- polr(anemia ~ contraceptive_group +  V012 +  V201 + V106 , Hess=TRUE, data = DHS_Contraceptive)

# odds ratios and 95%CIs
summary(model1_adj)
tidy(model1_adj, conf.int=TRUE, exponentiate = TRUE, p.values=TRUE)

OR <- exp(coef(model1_adj))
CI <- exp(confint(model1_adj))
cbind(OR, CI)
```




```{r}
#Reasearch objective 2
#To assess whether the association of anemia severity among non-pregnant women (15- 49 years) in Ghana is modified by hormonal contraceptive method type.


#Recoding the effect modifier variable(hormonal contraceptive method type)

DHS_Contraceptive$hormonal_type <- NA

DHS_Contraceptive$hormonal_type[DHS_Contraceptive$V312 == "Pill"] <- "Pill"
DHS_Contraceptive$hormonal_type[DHS_Contraceptive$V312 == "Injections"] <- "Injections"
DHS_Contraceptive$hormonal_type[DHS_Contraceptive$V312 == "Implants/Norplant"] <- "Implants"

# Everyone else (non-hormonal + no-method)
DHS_Contraceptive$hormonal_type[is.na(DHS_Contraceptive$hormonal_type)] <- "None"

table(DHS_Contraceptive$contraceptive_group, useNA = "ifany")
table(DHS_Contraceptive$hormonal_type, useNA = "ifany")

#Effect modfication model
model2 <- polr(
  anemia ~ contraceptive_group +  V012 +  V201 + V106 + hormonal_type + contraceptive_group * hormonal_type,
  data = DHS_Contraceptive,
  Hess = TRUE
)

table(DHS_Contraceptive$contraceptive_group, DHS_Contraceptive$hormonal_type)

summary(model2)

#Getting the p-value
(ctable <- coef(summary(model2)))
p_values <- 2 * pnorm(abs(ctable[, "t value"]), lower.tail = FALSE)
cbind(ctable, "p value" = p_values)


library(lmtest)
lrtest(model1_adj, model2)

getwd()

```

```{r}
#Subgroup analysis(hormonal method users only)
hormonal_only <- subset(DHS_Contraceptive, contraceptive_group == "Hormonal")

mod_hormonal <- polr(
  anemia ~ V012 +  V201 + V106 + hormonal_type, data = hormonal_only,
  Hess = TRUE
)

summary(mod_hormonal)
exp(cbind(OR = coef(mod_hormonal), confint(mod_hormonal)))
```

```{r}
##Checking proportional odds assumption
brant(model1_adj)

## Assumption voilated hence using
## Alternative models that do not impose the constraint of proportional odds, a multinomial logistic model
```

```{r}
#Running multinomial regression for research objective 1
Multimodel1 <- multinom(anemia ~ contraceptive_group, data = DHS_Contraceptive)
summary(Multimodel1)

# OR and CIs
tidy(Multimodel1, conf.int=TRUE, exponentiate = TRUE)
```

```{r}
#Adjusted for age(V012), parity(V201) and education(V106)
Multimodel1_adj <- multinom(anemia ~ contraceptive_group +  V012 +  V201 + V106 , data = DHS_Contraceptive)
summary(Multimodel1_adj)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel1_adj, conf.int=TRUE, exponentiate = TRUE)

```

```{r}
#Testing if model significantly improved
library(lmtest)
lrtest(Multimodel1, Multimodel1_adj)
```

```{r}
#Effect modfication model Research question 2
Multimodel2 <- multinom(anemia ~ contraceptive_group +  V012 +  V201 + V106 + hormonal_type + contraceptive_group * hormonal_type, data = DHS_Contraceptive)
summary(Multimodel2)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel2, conf.int=TRUE, exponentiate = TRUE)

library(lmtest)
lrtest(Multimodel1_adj, Multimodel2)


```

```{r}
#Subgroup analysis(hormonal method users only) with multinomial regression
hormonal_only <- subset(DHS_Contraceptive, contraceptive_group == "Hormonal")

Multimod_hormonal <- multinom(anemia ~ V012 +  V201 + V106 + hormonal_type, data = hormonal_only)
summary(Multimod_hormonal)

Multimod_hormonal_only <- multinom(anemia ~ hormonal_type, data = hormonal_only)
summary(Multimod_hormonal_only)

## extract coefficients from the model, exponentiate and CI
tidy(Multimod_hormonal_only, conf.int=TRUE, exponentiate = TRUE)
```
## Assumptions of multinomial logistic regression
```{r}
library(car)

# Checking multicolinerity
lm_check <- lm(as.numeric(anemia) ~ contraceptive_group + V012 + V201 + V106,
               data = DHS_Contraceptive)

vif(lm_check)
```
```{r}
##Checking for linearity in the logit assumption with numeric variables age and parity
install.packages("rcompanion")
library(rcompanion)

boxTidwell(as.numeric(anemia) ~ V012 + V201,
           data = DHS_Contraceptive)

##Assumption voilated hence using age catergorical varaible(V013) and categorizing parity too
```


```{r}
#Categorizing parity
DHS_Contraceptive$parity_cat <- cut(DHS_Contraceptive$V201,
                                    breaks = c(-1,2,4,6,20),
                                    labels = c("0-2","3-4","5-6","7+"))


```


```{r}
## Re-runing the multinomial adjusted and non adjusted model adjusting with catergorical variables of age and parity

Multimodel1_nonadj <- multinom(anemia ~ contraceptive_group, data = DHS_Contraceptive)
summary(Multimodel1_nonadj)

# OR and CIs
tidy(Multimodel1_nonadj, conf.int=TRUE, exponentiate = TRUE)

Multimodel1_adj2 <- multinom(anemia ~ contraceptive_group + V013 + parity_cat + V106,
                             data = DHS_Contraceptive)
summary(Multimodel1_adj2)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel1_adj2, conf.int=TRUE, exponentiate = TRUE)

table(DHS_Contraceptive$anemia)

#testing if model significantly improves after adjusting using catergorical variables of age and parity
library(lmtest)
lrtest(Multimodel1, Multimodel1_adj2)
```
```{r}
#Re-running effection modification model adjusting with catergorical variables of age and parity
#Reasearch objective 2
#To assess whether the association of anemia severity among non-pregnant women (15- 49 years) in Ghana is modified by hormonal contraceptive method type.


Multimodel3 <- multinom(anemia ~ contraceptive_group +  V013 + parity_cat + V106 + hormonal_type + contraceptive_group * hormonal_type, data = DHS_Contraceptive)
summary(Multimodel3)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel3, conf.int=TRUE, exponentiate = TRUE)

library(lmtest)
lrtest(Multimodel1_adj2, Multimodel3)

```


```{r}
table(hormonal_only$anemia)

with(hormonal_only, table(hormonal_type, anemia))
```


```{r}

# NOTE:
# Severe anemia was dropped from the effect modification model because the 
# hormonal-only subgroup contained extremely few severe cases (including zero 
# cases for some hormonal methods). This caused sparse cells and quasi-complete 
# separation in the multinomial model, leading to unstable and inflated estimates. 
# Removing the severe category ensures model convergence and valid parameter estimates.
# Drop severe anemia category for effect modification analysis
DHS_EM <- subset(DHS_Contraceptive, anemia %in% c("Not anemic", "Mild", "Moderate"))

# Check counts
table(DHS_EM$anemia)
```


```{r}
#Re-running effection modification model adjusting with catergorical variables of age and parity and after removing anemia severity category
#Reasearch objective 2
#To assess whether the association of anemia severity among non-pregnant women (15- 49 years) in Ghana is modified by hormonal contraceptive method type.

#Droping unused factor level(severe)
DHS_EM$anemia <- droplevels(DHS_EM$anemia)
#Running base-line model with no interaction

DHS_EM$anemia <- droplevels(DHS_EM$anemia)
Multimodel4 <- multinom(anemia ~ contraceptive_group +  V013 + parity_cat + V106 , data = DHS_EM)
summary(Multimodel4)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel4, conf.int=TRUE, exponentiate = TRUE)

DHS_EM$anemia <- droplevels(DHS_EM$anemia)
Multimodel5 <- multinom(anemia ~ contraceptive_group +  V013 + parity_cat + V106 + hormonal_type + contraceptive_group * hormonal_type, data = DHS_EM)
summary(Multimodel5)

## extract coefficients from the model, exponentiate and CI
tidy(Multimodel5, conf.int=TRUE, exponentiate = TRUE)

library(lmtest)
lrtest(Multimodel4, Multimodel5)
```


```{r}
##CHecking the types of contraceptives

table(DHS_Contraceptive$V312, useNA = "ifany")
```

```{r}
library(dplyr)
library(forcats)
library(haven)

# 1) Make sure V312 is readable as text labels
DHS_Contraceptive <- DHS_Contraceptive %>%
  mutate(
    method_raw = as_factor(V312)  
  )

# 2) Create the exposure variable with method-specific levels + grouped small categories
DHS_Contraceptive <- DHS_Contraceptive %>%
  mutate(
    contra_type = case_when(
      method_raw %in% c("Not using", "No method") ~ "No method",

      # Major specific methods (keep separate)
      method_raw == "Pill" ~ "Pill",
      method_raw == "Injections" ~ "Injection",
      method_raw == "Implants/Norplant" ~ "Implant",
      method_raw == "IUD" ~ "IUD",
      method_raw == "Male condom" ~ "Male condom",
      method_raw == "Female sterilization" ~ "Female sterilization",

      # Group: Traditional methods (combine)
      method_raw %in% c("Periodic abstinence",
                        "Withdrawal",
                        "Standard days method (SDM)",
                        "Other traditional") ~ "Traditional methods",

      # Group: Other modern methods (combine small/episodic)
      method_raw %in% c("Emergency contraception",
                        "Other modern method") ~ "Other modern methods",

      # Zero-count / not present / rare categories: set to NA (exclude later)
      method_raw %in% c("Diaphragm",
                        "Female condom",
                        "Foam or jelly",
                        "Male sterilization",
                        "Prolonged abstinence",
                        "Specific method 1",
                        "Specific method 2") ~ NA_character_,

      # Anything unexpected
      TRUE ~ NA_character_
    ),

    # 3) Convert to factor and set reference category
    contra_type = factor(
      contra_type,
      levels = c("No method",
                 "Pill",
                 "Injection",
                 "Implant",
                 "IUD",
                 "Male condom",
                 "Female sterilization",
                 "Traditional methods",
                 "Other modern methods")
    )
  )

# Optional: check counts
table(DHS_Contraceptive$contra_type, useNA = "ifany")
```

```{r}
DHS_Contraceptive <- DHS_Contraceptive %>%
  mutate(
    contra_type = case_when(
      method_raw %in% c("Not using", "No method") ~ "No method",

      method_raw == "Pill" ~ "Pill",
      method_raw == "Injections" ~ "Injection",
      method_raw == "Implants/Norplant" ~ "Implant",
      method_raw == "IUD" ~ "IUD",
      method_raw == "Male condom" ~ "Male condom",
      method_raw == "Female sterilization" ~ "Female sterilization",

      # Add LAM explicitly
      method_raw == "Lactational amenorrhea (LAM)" ~ "LAM",

      method_raw %in% c("Periodic abstinence",
                        "Withdrawal",
                        "Standard days method (SDM)",
                        "Other traditional") ~ "Traditional methods",

      method_raw %in% c("Emergency contraception",
                        "Other modern method") ~ "Other modern methods",

      # truly zero/rare/unobserved types remain NA
      method_raw %in% c("Diaphragm",
                        "Female condom",
                        "Foam or jelly",
                        "Male sterilization",
                        "Prolonged abstinence",
                        "Specific method 1",
                        "Specific method 2") ~ NA_character_,

      TRUE ~ NA_character_
    ),
    contra_type = factor(
      contra_type,
      levels = c("No method",
                 "Pill",
                 "Injection",
                 "Implant",
                 "IUD",
                 "Male condom",
                 "Female sterilization",
                 "LAM",
                 "Traditional methods",
                 "Other modern methods")
    )
  )

table(DHS_Contraceptive$contra_type, useNA = "ifany")
```
```{r}
with(DHS_Contraceptive, table(contra_type, anemia))
```

```{r}
library(dplyr)

DHS_Contraceptive <- DHS_Contraceptive %>%
  mutate(
    anemia3 = case_when(
      anemia == "Not anemic" ~ "Not anemic",
      anemia == "Mild" ~ "Mild",
      anemia %in% c("Moderate", "Severe") ~ "Moderate/Severe",
      TRUE ~ NA_character_
    ),
    anemia3 = factor(anemia3, levels = c("Not anemic", "Mild", "Moderate/Severe"))
  )

# Check the new counts
with(DHS_Contraceptive, table(contra_type, anemia3, useNA = "ifany"))
```

```{r}
##Unadjusted model
Multimodel7 <- multinom(anemia3 ~ contra_type, data = DHS_Contraceptive)
summary(Multimodel7)
```

```{r}
Multimodel6 <- multinom(anemia3 ~ contra_type +  V013 + parity_cat + V106, data = DHS_Contraceptive)
summary(Multimodel6)
```

